# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Photos
  description: Photos
  icon: "photo"
  tags: ["gallery"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Gallery Title
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fermentum tempor consectetur. Donec gravida nec quam sed venenatis. Ut mattis iaculis magna, quis commodo purus dictum non.
  collections:
    - collection: /collection/nyt-golf.md
    - collection: /collection/the-court-md

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  images:
    type: array

