# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Photo
  description: Add a photo to a collection.
  icon: "image"
  tags: ["collection"]
  preview:
    image:
      - key: image_path
    text:
      - key: alt_text
      - Photo

# Defines the structure of this component, as well as the default values
blueprint:
  image_path: /images/gallery/1.jpg
  alt_text: Image Alt Text

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  image_path:
    type: image
  alt_text:
    type: text

