# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Text
  description: Add text to a collection.
  icon: "edit_note"
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Gallery Title
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fermentum tempor consectetur. Donec gravida nec quam sed venenatis. Ut mattis iaculis magna, quis commodo purus dictum non.
  images:
    - image_path: /images/gallery/1.jpg
      alt_text: Image 1
    - image_path: /images/gallery/2.jpg
      alt_text: Image 2
    - image_path: /images/gallery/3.jpg
      alt_text: Image 3

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  images:
    type: array

